### The BEGINNING ~~~~~
##
# ~ Plots --per-position depth distribution in order to set up reasonable depth filters. | First written by Nicolas Lou with later modifications by Homère J. Alves Monteiro

rm(list = ls(all = TRUE))

pacman::p_load(tidyverse, cowplot, knitr, RcppCNPy, scales, MetBrewer, ade4)

setwd("~/Desktop/Scripts/Cult.vs.Wild/")
#### depth distribution obtained from ANGSD to establish depth filters for SNP calling. ####
depth_hist_angsd <- read_lines("~/Desktop/Scripts/Data/Cult.vs.Wild/AngsdFilters//qsubApr23_baq_mincov_minq20_minmapq20.depthGlobal") %>%
  str_split(pattern = "\t") %>%
  .[[1]] %>%
  .[1:2001] %>%
  as.integer() %>%
  tibble(depth=0:2000, count=., method="angsd")
histo_distrib_2<- depth_hist_angsd %>%
  filter(depth>0, depth<2100) %>%
  ggplot(aes(x=depth, y=count, color=method)) +
  geom_freqpoly(stat = "identity") +
  theme_cowplot()
ggsave(histo_distrib_2, file = "Figures/SetAngsdFilters/per-position_depth_distrib.pdf",  scale = 1.1, width = 12, height = 8, dpi = 300)
dev.off()
# 147 is the mode of the peak using ANGSD
filter(depth_hist_angsd, depth>10) %>%
  group_by(method) %>%
  slice_max(order_by = count)

#### Find the standard deviation of the peak by fitting the right part of it to a normal distribution. #### 
sd_table <- NULL
# Calculate residual sum of squares by iterating through a range of possible standard devation values
for (standard_deviation in 5:95){
  x <- filter(depth_hist_angsd, depth>=147, depth<=500) %>%
    mutate(temp=dnorm(depth, mean=147, sd=standard_deviation)) %>%
    mutate(count_fitted=temp*6132600/max(temp)) %>%
    summarise(rss=sum((count-count_fitted)^2)) %>%
    mutate(sd=standard_deviation)
  sd_table=bind_rows(sd_table, x)
}
# Find the standard deviation value with the lowest RSS
optimal_sd <-slice_min(sd_table, rss, n = 1)$sd
optimal_sd
#> optimal_sd
#[1] 37
sd_table %>%
  ggplot(aes(x=sd, y=rss)) +
  geom_line()
# fit right part or the distrib to normal distribution
fit_norm <- filter(depth_hist_angsd, depth>1, depth<=500) %>%
  mutate(temp=dnorm(depth, mean=147, sd=optimal_sd)) %>%
  mutate(count_fitted=temp*6132600/max(temp)) %>%
  ggplot(aes(x=depth, y=count)) +
  geom_freqpoly(stat = "identity") +
  geom_freqpoly(aes(y=count_fitted), stat = "identity", color="blue") +
  theme_cowplot()
ggsave(fit_norm, file = "Figures/SetAngsdFilters/Fit_normal_per-position_depth_distrib.pdf", device = cairo_pdf, scale = 1.1, width = 12, height = 8, dpi = 300)
dev.off()
#The fitted normal distribution doesn't match the empricial depth distribution quite well.

#### Use two standard deviations from the mode as depth cutoffs #### 
depth_hist_angsd <- depth_hist_angsd %>% drop_na()
## If a MaxDepth=221 filter is used (shown below), ~3.6% of all sites and ~9.1% of the final mapped data will be lost
max_depth <- 147 + 2*optimal_sd # =221
sum(filter(depth_hist_angsd, depth>max_depth)$count)/sum(depth_hist_angsd$count)
sum(filter(depth_hist_angsd, depth>max_depth)$count*filter(depth_hist_angsd, depth>max_depth)$depth)/sum(depth_hist_angsd$count*depth_hist_angsd$depth)

## If a MinDepth=73 filter is used (shown below), ~25.5% of all sites and ~7% of the final mapped data will be lost
min_depth <- 147 - 2*optimal_sd
sum(filter(depth_hist_angsd, depth<min_depth)$count)/sum(depth_hist_angsd$count)
sum(filter(depth_hist_angsd, depth<min_depth)$count*filter(depth_hist_angsd, depth<min_depth)$depth)/sum(depth_hist_angsd$count*depth_hist_angsd$depth)


## If these filters are used
cut_off_norm <-filter(depth_hist_angsd, depth>1, depth<=2000) %>%
  ggplot(aes(x=depth, y=count)) +
  geom_freqpoly(stat = "identity") +
  geom_vline(xintercept = c(max_depth,min_depth), color="red") +
  theme_cowplot()
ggsave(cut_off_norm, file = "Figures/SetAngsdFilters/cutoffMinMaxDepthFit_normal_per-position_depth_distrib.pdf", device = cairo_pdf, scale = 1.1, width = 12, height = 8, dpi = 300)
dev.off()




#### Set up minimum individual filters #### 
#The distribution of numbers of individuals being present at each site is available from the mafs.gz file generated by ANGSD. Note that the mafs.gz file is very large and this step can be very memory consuming (~55GB for this dataset).

nind_angsd <- read_tsv("~/Desktop/Scripts/Data/Cult.vs.Wild/AngsdFilters/qsubApr23_baq_mincov_minq20_minmapq20.presenceGlobal")
nind_angsd %>%
  slice_max(n)
# A tibble: 1 × 2
#nInd       n
#<dbl>   <dbl>
#  1   450 6116239

#The mode of the second peak is Let’s not  use the minInd filter 
# numbers of individuals being present at each site is available.
## minInd=75
nind_angsd %>%
  ggplot(aes(x=nInd, y=n)) +
  geom_freqpoly(stat = "identity") +
  geom_vline(xintercept = 221/4, color="purple") +
  theme_cowplot()
ggsave(nind_angsd, file = "Figures/SetAngsdFilters/minInd_cutoffdistrib_numbers_individualperSite.pdf", device = cairo_pdf, scale = 1.1, width = 12, height = 8, dpi = 300)
dev.off()

